axon:
  eventhandling:
    processors:
      amqpEvents:
        source: orderEvents

  amqp:
    exchange: ShipmentEvents

# H2DB
spring:
  datasource:
    url: jdbc:h2:file:~/workspace/orderDB;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver

# Spring properties
#spring:
#  application:
#     name: order-service
#
## Discovery Server Access
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/
#
## HTTP Server
#server:
#  port: 2222   # HTTP (Tomcat) port
