axon:
  eventhandling:
    processors:
      amqpEvents:
        source: orderEvents

  amqp:
    exchange: ShipmentEvents

  distributed:
    enabled: true

# H2DB
spring:
  datasource:
    url: jdbc:h2:file:~/workspace/orderDB;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver

  application:
     name: order-service

  cloud:
    services:
      registrationMethod: route

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 8080
